.PHONY: all build start-test stop

all: stop build start

build:
	./common-bin/build.sh

start:
	./common-bin/start.sh

stop:
	./common-bin/stop.sh

snapshot:
	./common-bin/snapshot.sh

status:
	./common-bin/status.sh